config/routes.rb
Worklog::Application.routes.draw do

  resources :jobs

  resources :products

  resources :locations

  resources :entities

  get 'faq', to: 'pages#faq', as: 'faq'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :users

  root to: 'pages#home'

end

app/models/entity.rb
class Entity < ActiveRecord::Base
	has_many :jobs
  	attr_accessible :name

  	validates_presence_of :name
  	validates_uniqueness_of :name
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  # GET /entities
  # GET /entities.json
  def index
    @entities = Entity.paginate(page: params[:page]).per_page(25)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entities }
      format.js
    end
  end

  # GET /entities/1
  # GET /entities/1.json
  def show
    @entity = Entity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entity }
    end
  end

  # GET /entities/new
  # GET /entities/new.json
  def new
    @entity = Entity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entity }
    end
  end

  # GET /entities/1/edit
  def edit
    @entity = Entity.find(params[:id])
  end

  # POST /entities
  # POST /entities.json
  def create
    @entity = Entity.new(params[:entity])

    respond_to do |format|
      if @entity.save
        format.html { redirect_to @entity, notice: 'Entity was successfully created.' }
        format.json { render json: @entity, status: :created, location: @entity }
      else
        format.html { render action: "new" }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entities/1
  # PUT /entities/1.json
  def update
    @entity = Entity.find(params[:id])

    respond_to do |format|
      if @entity.update_attributes(params[:entity])
        format.html { redirect_to @entity, notice: 'Entity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1
  # DELETE /entities/1.json
  def destroy
    @entity = Entity.find(params[:id])
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to entities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_entity.html.erb
<tr>
	<td><%= entity.name %></td>
	<td><%= link_to "view", entity %> | <%= link_to "delete", entity, method: :delete, data: { confirm: "You sure?" } %></td>
</tr>

app/views/entities/_form.html.erb
<%= simple_form_for(@entity, :html => {:class => 'form-horizontal' }) do |f| %>
  <%= f.input :name, :label => 'Entity Name:' %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
  </div>
<% end %>

app/views/entities/edit.html.erb
<div class="row">
	<div class="span12 vspacerf">
	    <h3 style="display:inline;">Edit Entity</h3>
	    <div class="pull-right">
	        <%= link_to 'Show', @entity %> | <%= link_to 'Back', entities_path %>
	    </div>
	</div>
</div>
<div class="row">
	<div class="span6 offset3 vspacera well">
		<%= render 'form' %>
	</div>
</div>

app/views/entities/index.html.erb
<div class="row">
    <div class="span12 vspacerf">
        <h3 style="display:inline;">Entities</h3>
        <div class="btn-group pull-right">
            <button class="btn btn-success"><i class="icon-cog"></i> Actions</button>
            <button class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li><%= link_to 'New Entity', new_entity_path %></li>
            </ul>
        </div>
    </div>
</div>
<div class="row">
    <div class="span12 vspacerf">
        <% if @entities.count < 1 %>
            <h3>You have not entered any Entities yet.  <%= link_to 'Enter One Now', new_entity_path %></h3>
        <% else %>
            <table class="table">
                <thead>
                    <th>Name</th>
                    <th>Action</th>
                </thead>
                <tbody id="entities">
                    <%= render @entities %>
                </tbody>
            </table>

            <%= will_paginate @entities %>
        <% end %>
    </div>
</div>

app/views/entities/index.js.erb
$('#entities').append('<%= j render(@entities) %>');
<% if @entities.next_page %>
$('.pagination').replaceWith('<%= j will_paginate(@entities) %>');
<% else %>
$('.pagination').remove();
<% end %>
<% sleep 1 %>

app/views/entities/new.html.erb
<div class="row">
	<div class="span12 vspacerf">
	    <h3 style="display:inline;">New Entity</h3>
	    <div class="pull-right">
	        <%= link_to 'Back', entities_path %>
	    </div>
	</div>
</div>
<div class="row">
	<div class="span6 offset3 vspacera well">
		<%= render 'form' %>
	</div>
</div>

app/views/entities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @entity.name %>
</p>


<%= link_to 'Edit', edit_entity_path(@entity) %> |
<%= link_to 'Back', entities_path %>