config/routes.rb
Worklog::Application.routes.draw do

  resources :jobs

  resources :products

  resources :locations

  resources :entities

  get 'faq', to: 'pages#faq', as: 'faq'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :users

  root to: 'pages#home'

end

app/views/shared/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
             
            <!-- Be sure to leave the brand out there if you want it shown -->
            <!-- <a class="brand" href="#">WorkLog</a> -->
            <div class="logo hidden-phone">
                <%= link_to root_url, class: 'brand' do %>
                    <i class="icon-truck">   </i>
                <% end %>
            </div>
            <%= link_to root_url, class: 'brand visible-phone' do %>
                <i class="icon-truck">   </i>
            <% end %>
            <% if current_user %><%= yield :search %><% end %>
            <!-- Everything you want hidden at 940px or less, place within here -->
            <div class="nav-collapse collapse">
                <ul class="nav pull-right">
                    <% if current_user %>
                        <li class="divider-vertical"></li>
                        <li>
                            <%= link_to jobs_path do %>
                                <i class="icon-check"></i>
                                Jobs
                            <% end %>
                        </li>
                        <li class="divider-vertical"></li>
                        <li>
                            <%= link_to users_path do %>
                                <i class="icon-user"></i>
                                Users
                            <% end %>
                        </li>
                        <li class="divider-vertical"></li>
                        <li>
                            <%= link_to entities_path do %>
                                <i class="icon-sitemap"></i>
                                Entities
                            <% end %>
                        </li>
                        <li class="divider-vertical"></li>
                        <li>
                            <%= link_to locations_path do %>
                                <i class="icon-map-marker"></i>
                                Locations
                            <% end %>
                        </li>
                        <li class="divider-vertical"></li>
                        <li>
                            <%= link_to products_path do %>
                                <i class="icon-shopping-cart"></i>
                                Products
                            <% end %>
                        </li>
                        <li class="divider-vertical"></li>
                        <li>
                            <%= link_to session_path("current"), method: "delete" do %>
                                <i class="icon-signout"></i>
                                Log Out
                            <% end %>
                        </li>
                        <li class="divider-vertical"></li>
                    <% else %>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</div>